[project]
name = "agents-playground"
version = "0.1.0"
description = "Playground to explore AI Agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
    "smolagents>=1.8.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
